# Generated by Django 3.0.4 on 2020-12-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_auto_20201212_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamscoring',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='teamscoring',
            name='tie',
        ),
        migrations.RemoveField(
            model_name='teamscoring',
            name='wins',
        ),
        migrations.AddField(
            model_name='teamscoring',
            name='options',
            field=models.CharField(choices=[('wins', 'wins'), ('loss', 'loss'), ('ties', 'ties')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
