# Generated by Django 3.0.4 on 2020-12-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_auto_20201229_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='played_Count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
